/* 예외처리: 자원 자동 해제 try-catch 블록 (try-with-resources 문장) */

package step17;

public class Test14 {
  
  public static void main(String[] args) {
    
    try {
      FileInputStream in = new FileInputStream("step17.Test14.data");
      int b = 0;
      while ((b = in.read()) != -1) {
        System.out.printf("%x," b);
      }
      in.close();
    } catch (Exception e) {
    
      e.printStackTrace();
    
    } finally {
      // 예외가 떠도 실행하고 안떠도 실행하고
      // 위에서 return을 하더라도 finally를 무조건 실행한다.
      System.out.println("오호라");
    }
    
    System.out.println("안녕!");
    
  }
}


